services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=coolify
      - traefik.http.services.qkd.loadbalancer.server.port=80
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: '${APP_URL}'
      APP_KEY: '${APP_KEY}'

      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: '${DB_DATABASE}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - app2_storage:/var/www/html/storage
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal
      - coolify

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
    volumes:
      - app2_db:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  app2_storage:
  app2_db:

networks:
  internal:
    driver: bridge
  coolify:
    external: true